---
cyberark:
  members: []
  channel: "#development"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

  exclude_repos:
    - epv-api-scripts
    - urbancode-conjur-aim
    - cyberark-aws-auto-onboarding
    - shimit
